### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by zakzak1248** [MatsoA/CIS-427-Project-1#3]
Hello,

Thank you for your interest in this project. In regards to rewriting the project in Rust, we would like to encourage community contributions and suggestions. Rust is a great language and offers many benefits such as performance and safety guarantees.

However, before embarking on a complete rewrite, we would like to consider a few important factors. Firstly, we need to make sure that the existing functionality is preserved in the new implementation. Additionally, we need to consider the amount of resources and time required for the rewrite, as well as the impact it may have on the existing user base.

If you have any thoughts or suggestions on this matter, we would be happy to hear them. Together, we can ensure that the rewrite will benefit the project in the best way possible.

Best regards,
[Your Name]

**Comment by MatsoA** [comment]
I agree with this sentiment, we'll look into it at a later date

Regards,
[My Name]
